# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: zcugni <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/11/08 09:53:59 by zcugni            #+#    #+#              #
#    Updated: 2017/11/20 09:50:33 by zcugni           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a
SRCS =  ft_isalnum.c ft_isprint.c ft_strcat.c ft_strdup.c ft_strncmp.c \
		ft_strstr.c ft_isalpha.c ft_memccpy.c ft_strchr.c ft_strlcat.c \
		ft_strncpy.c ft_tolower.c ft_atoi.c ft_isascii.c ft_memcpy.c \
		ft_strcmp.c ft_strlen.c ft_strnstr.c ft_toupper.c ft_bzero.c \
		ft_isdigit.c ft_memset.c ft_strcpy.c ft_strncat.c ft_strrchr.c \
		ft_memmove.c ft_memchr.c ft_memcmp.c ft_memalloc.c ft_memdel.c \
		ft_strnew.c ft_strdel.c ft_strclr.c ft_striter.c ft_striteri.c \
		ft_strmap.c ft_strmapi.c ft_strequ.c ft_strnequ.c ft_strsub.c \
		ft_strjoin.c ft_strtrim.c ft_strsplit.c ft_putchar.c is_neg.c  \
		ft_putstr.c ft_putendl.c ft_putnbr.c ft_putchar_fd.c ft_putstr_fd.c \
		ft_putendl_fd.c ft_putnbr_fd.c ft_pow.c ft_strndup.c ft_strsub_free.c \
		ft_strjoin_free.c get_next_line.c ft_strchri.c ft_get_leaks.c

OBJS = $(SRCS:.c=.o)

FLAG = -Wall -Werror -Wextra

all: $(NAME)

$(NAME): $(OBJS)
	ar rc $(NAME) $(OBJS)
	ranlib $(NAME)

%.o: %.c
	gcc $(FLAG) -c $< -I libft.h

clean:
	rm -f $(OBJS)

fclean: clean
	rm -f $(NAME)

re : fclean all

.PHONY: clean fclean all re
